server:
  port: 80

spring:


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

logging:
  level:
    com.tradin.module.feign.client: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  api-docs:
    path: /v1/api-docs
  default-produces-media-type: application/json
  override-with-generic-response: true
  writer-with-default-pretty-printer: true

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000

secret:
  aes-secret: ${AES_SECRET_KEY}
  cognito-client-id: ${COGNITO_CLIENT_ID}
  cognito-auth-redirect-uri: ${COGNITO_AUTH_REDIRECT_URI}
  cognito-issuer: ${COGNITO_ISSUER}
  swagger-username: ${SWAGGER_USERNAME}
  swagger-password: ${SWAGGER_PASSWORD}